#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World' | sudo tee '/var/www/html/index.nginx-debian.html'
search="^\tlocation / {"
string="\tlocation /redirect_me {\n\t\t return 301 \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$search@$string@" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
