#!/usr/bin/env bash
# Fizzin and Buzzin
i="1"
while (( i <=100 ))
do
    if
	(( i % 3 == 0 && i % 5 == 0 ))
    then
        echo "FizzBuzz"
        i=$(( i + 1 ))
    elif (( i % 3 == 0 ))
	 then
	echo "Fizz"
	i=$(( i + 1 ))
    elif (( i % 5 == 0 ))
    then
	echo "Buzz"
	i=$(( i + 1 ))
    else
	echo "$i"
	i=$(( i + 1 ))
    fi
done    
   
