#!/usr/bin/env bash
# 1-20; bad luck from China, Japan, Italy
i="1"
while (( i <= 20 ))
do
    echo "$i"
      i=$(( i + 1 )) ; 

      case $i in
	  5) echo "bad luck from China" ;;
	  10) echo "bad luck from Japan" ;;
	  18) echo "bad luck from Italy" ;;
      esac

done

