#!/usr/bin/env bash
# Install nginx web server

# Install HAproxy
sudo apt update
sudo apt install -y haproxy

frontend="\nfrontend myproxy\n\tbind:80\n\tdefault_backend web_servers\n"
sudo echo -e "$frontend" | sudo tee -a /etc/haproxy/haproxy.cfg

backend="\nbackend web_servers\n\tbalance roundrobin\n\tserver 3597-web-01 54.167.103.210:80\n\tserver 3597-web-02 54.221.139.18:80"
sudo echo -e "$backend" | sudo tee -a /etc/haproxy/haproxy.cfg
