#!/usr/bin/env bash
# Install HAproxy

# Install HAproxy
sudo apt update
sudo apt install -y haproxy

# Create frontend block, append to config file
frontend="\nfrontend myproxy\n\tbind:80\n\tdefault_backend web_servers\n"
echo -e "$frontend" | sudo tee -a /etc/haproxy/haproxy.cfg

# Create backend block, append to config file
backend="\nbackend web_servers\n\tbalance roundrobin\n\tserver web-01 54.167.103.210:80\n\tserver web-02 54.221.139.18:80"
echo -e "$backend" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
