#!/usr/bin/env bash
# Iterations 1 to 10 Holberton School, loop 4 bad luck, loop 8 goodluck
i="1"
while
[ $i -lt 9 ] ;
do
    echo "Holberton School"
    i=$(( $i + 1 ))
if
[ $i -eq 4 ]
then
echo "bad luck"
elif
[ $i -eq 7 ]
then
    echo "good luck"
else
   continue
   fi
done
